service: aws-lambda-crud-node
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:740217048153:table/TaskTable

functions:
  hello:
    handler: src/handlers/hello.hello
    events:
      - httpApi:
          path: /
          method: GET

  create-task:
    handler: src/handlers/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: POST

  get-tasks:
    handler: src/handlers/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: GET

  get-task:
    handler: src/handlers/getTask.getTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: GET

  update-task:
    handler: src/handlers/updateTask.updateTask
    events: 
      - httpApi:
          path: /tasks/{id}
          method: PUT

  delete-task:
    handler: src/handlers/deleteTask.deleteTask
    events: 
      - httpApi:
          path: /tasks/{id}
          method: DELETE

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
